name: Go

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v ./...

    - uses: google-github-actions/setup-gcloud@v2
      with:
        version: '>= 486.0.0'
        install_components: 'cloud-firestore-emulator'

    - name: Start Firestore emulator
      run: |
        gcloud emulators firestore start --host-port=[::1]:8410 &

        until curl '[::1]:8410' 2>/dev/null; do
            sleep 1
        done

    - name: Test
      run: go test -v ./...
      env:
        FIRESTORE_EMULATOR_HOST: '[::1]:8410'
